export const DATA_COLUMNS = [
  // { type: 'checkbox', noEditor: true, showInColumnChooser: false, visible: false, isRowSelector: true },
  {
    field: 'taskID',
    headerText: 'Task ID1',
    textAlign: 'Left',
    type: 'string',
    visible: false,
    noEditor: true,
    isPrimaryKey: true,
    showInColumnChooser: false,
    customAttributes: { class: 'header-column-font1' },
    backgroundColor: '#fff',
    allowEditing: false,
  },
  {
    field: 'taskCode',
    headerText: 'Task ID',
    textAlign: 'Left',
    type: 'string',
    allowEditing: false,
    width: 150,
    minWidth: 150,
    fontSize: 14,
    color: '#757575',
    textWrap: 'normal',
    customAttributes: { class: 'header-column-font2' },
    backgroundColor: '#fff',
  },
  {
    field: 'taskName',
    headerText: 'Task Name',
    textAlign: 'Left',
    type: 'string',
    fontSize: 14,
    width: 150,
    minWidth: 150,
    color: '#757575',
    textWrap: 'normal',
    customAttributes: { class: 'header-column-font3' },
    backgroundColor: '#fff',
    allowEditing: true,
  },
  {
    field: 'startDate',
    headerText: 'Start Date',
    textAlign: 'Left',
    format: 'MM/dd/yyyy',
    editType: 'datetimepickeredit',
    type: 'date',
    fontSize: 14,
    width: 150,
    minWidth: 150,
    color: '#757575',
    textWrap: 'normal',
    customAttributes: { class: 'header-column-font4' },
    backgroundColor: '#fff',
    allowEditing: true,
  },
  {
    field: 'duration',
    headerText: 'Duration',
    textAlign: 'Left',
    type: 'number',
    fontSize: 14,
    width: 150,
    minWidth: 150,
    color: '#757575',
    textWrap: 'normal',
    customAttributes: { class: 'header-column-font5' },
    backgroundColor: '#fff',
  },
  // {
  //   type: '',
  //   displayAsCheckBox : true,
  //   width: 60,
  //   visible: false,
  //   allowFiltering : false,
  //   showInColumnChooser: false,
  //   isSelectRowCell : true,
  //   allowEditing: false,
  // },
];
