export const DATA_COLUMNS = [
  {
    field: 'taskID',
    headerText: 'Task ID1',
    textAlign: 'Left',
    type: 'string',
    visible: false,
    isPrimaryKey: true,
    fontSize: 14,
    color: '#757575',
    textWrap: 'normal',
    showInColumnChooser: false,
    customAttributes: { class: 'header-column-font1' },
  },
  {
    field: 'taskCode',
    headerText: 'Task ID',
    textAlign: 'Left',
    type: 'string',

    fontSize: 14,
    color: '#757575',
    textWrap: 'normal',
    customAttributes: { class: 'header-column-font2' },
  },
  {
    field: 'taskName',
    headerText: 'Task Name',
    textAlign: 'Left',
    type: 'string',
    fontSize: 14,
    color: '#757575',
    textWrap: 'normal',
    customAttributes: { class: 'header-column-font3' },
  },
  {
    field: 'startDate',
    headerText: 'Start Date',
    textAlign: 'Left',
    format: 'yMd',
    editType: 'datetimepickeredit',
    type: 'date',
    fontSize: 14,
    color: '#757575',
    textWrap: 'normal',
    customAttributes: { class: 'header-column-font4' },
  },
  {
    field: 'duration',
    headerText: 'Duration',
    textAlign: 'Left',
    type: 'number',
    fontSize: 14,
    color: '#757575',
    textWrap: 'normal',
    customAttributes: { class: 'header-column-font5' },
  },
];
