export const CONTEXT_MENU_ITEM = [
  { text: 'Show/Hide Column', target: '.e-headercontent', id: 'show-hide-column' },
  { text: 'Add', target: '.e-headercontent', id: 'add' },
  { text: 'Edit', target: '.e-headercontent', id: 'edit' },
  { text: 'Delete', target: '.e-headercontent', id: 'delete' },
  { text: 'Multiple sorting off', target: '.e-headercontent', id: 'mutiple-sorting' },
  { text: 'Freeze', target: '.e-headercontent', id: 'freeze' },
  { text: 'Filter Off', target: '.e-headercontent', id: 'filter' },
  { text: 'Styling', target: '.e-headercontent', id: 'styling' },
  { text: 'Copy with headers', target: '.e-content', id: 'copywithheader' },
  'Copy',
  { text: 'Copy selected rows', target: '.e-content', id: 'copyrows' },
  { text: 'Cut', target: '.e-content', id: 'cut' },
  { text: 'Paste as sibling', target: '.e-content', id: 'pastesibling' },
  { text: 'Paste as child', target: '.e-content', id: 'pasteschild' },
  { text: 'Turn off multi select mode', target: '.e-content', id: 'multiselect' },

  'AddRow',
  'Edit',
  'Delete',
  'Save',
  'Cancel',
];
